repos:
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3
        args:
          - "-l"
          - "120"
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-import-order
          - flake8-docstrings
          - pep8-naming
          - flake8-copyright
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: mixed-line-ending
        args:
          - "--fix=lf"
      - id: name-tests-test
        args:
          - "--unittest"
