name: pre-commit-and-test
on: [push]
env:
  ACR_REGISTRY: crkisharedi.azurecr.io
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1
